-- ============================================
-- DADOS INICIAIS - Contas Bancárias e Lançamentos
-- ============================================
-- Dados de demonstração removidos intencionalmente.
-- A aplicação inicia sem contas bancárias nem lançamentos de exemplo;
-- o usuário cadastra os próprios dados ao configurar a empresa.
-- (Migração mantida vazia para preservar o histórico de schema_migrations.)
-- ============================================
